# -*- coding: utf-8 -*-
"""Project_74.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M0fy4y5ARQydFq1eVic2hPQ3rJc5OkTt
"""

!pip3 install ipympl
#FOR CREATING INTERACTING MATPLOTLIB
#matplotlib ka extension for responsive diagram

import cv2
import matplotlib.pyplot as plt
import numpy as np
import math
#import pydicom
import scipy.ndimage.filters as fi
from scipy.signal import savgol_filter
import scipy.interpolate as intp
#import DynamicProgramming as DP


from mpl_toolkits import mplot3d
import os.path
import plotly.graph_objects as go

from datetime import datetime
from google.colab import files
from IPython.display import HTML, display

# Commented out IPython magic to ensure Python compatibility.


# %matplotlib widget
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# for 3D graph interaction

from google.colab import output
output.enable_custom_widget_manager()

# for 3D graph interaction

LOCAL = 20
RADIUS, SPREAD = 16, 4
RMIN, RMAX = 5, 80
MASK_SIZE = 3
mask = np.array([-1] * MASK_SIZE + [1] * MASK_SIZE) / MASK_SIZE
MAX_NODE = 3
DISPLAY = False
plt.set_cmap('gray')  # to set default colour for matplotlib to gray

#path="/content/"
path="/content/sample_data/patient 3/"

import sys      # to check if the program is running in debug mode or not
def showImage(im, title=None, numWin = None, show=True):
   # if 'pydevd' in sys.modules and DISPLAY:     # The variable pydevd is true if program is running in debug mode
        if numWin != None: plt.subplot(numWin)
        plt.imshow(im)
        plt.title(title)
        print ('hello ')
        if show:
            plt.show()
            plt.waitforbuttonpress()
            plt.close()
            return
# show image in a graph

def templateMatching(img, tpl):    #It uses numpy array multiplication and summation which is very fast
    ims = img.shape
    ts = tpl.shape
    ts = ts[0]//2, ts[1]//2
    corIm = np.zeros(ims, int)
    for r in range(ts[0], ims[0]-ts[0]):
        for c in range(ts[1], ims[1]-ts[1]):
            subim = img[r-ts[0]:r+ts[0]+1, c-ts[1]:c+ts[1]+1]
            corr = np.sum(subim * tpl)
            corIm[r, c] = corr
    return (corIm)
#temp matching is used for  identyfing artries in the image

#MATH OPERATION ON IMAGE ARRAY

def plotLineHisto(line, width=None):   #Summaation of pixels in a sub-window of width X width in the image is available in corSum
    plt.plot(line), plt.show(block=False)
    plt.text(50, 50, 'width = {}'.format(width))
    plt.waitforbuttonpress()
    plt.close()
#some values are cpming
#to see those values

def deleteLocMax(img, loc):
    x, y = loc[0], loc[1]
    img[y-LOCAL:y+LOCAL, x-LOCAL:x+LOCAL] = 0
#deleting parts of images
#CHANING PIXEL TO 0

# it finds sum of all positive correlation values in a sub-window of increasing size till it reaches peak value
def findMaxRegion(cimg):
    h, w = cimg.shape[0:2]
    max = cimg.max()
    maxloc = np.argmax(cimg)
    RMAX = maxloc // w
    cmax = maxloc - RMAX * w
    return ((cmax, RMAX), max)

def showResult(img, tpl, loc):
    global DISPLAY
    tpl -= np.min(tpl)
    tpl = (tpl * 255) // np.max(tpl)
    h, w  = tpl.shape    #size of template after resizing that was found in image
    x, y = loc[0] - w//2, loc[1]-h//2 #location of template
    alpha = 0.75
    resIm = img.copy()
    for r in range(h):
        for c in range(w):
            resIm[y+r, x+c] = alpha * resIm[y+r, x+c] + (1-alpha) * tpl[r,c]

    showImage(resIm, 'template superimposed', show=True)

    #templete making code

def LoGDisc(radedge, sigma=3, plot=True):
    gsize = sigma * 3
    rad = radedge + 4*sigma
    circularEdge = np.ones((2 * rad + 1, 2 * rad + 1), float)

    gaussian = np.zeros((2 * gsize + 1, 2 * gsize + 1), float)
    gaussian [ gsize, gsize] = 1
    gaussian = fi.gaussian_filter ( gaussian, sigma)
 #   if plot: showImage(gaussian, 'Gaussian', show=True)
  #  if plot: plotLineHisto(gaussian[gsize])
    LoGTpl = cv2.Laplacian(gaussian, cv2.CV_64F, ksize=3)
   # if plot: showImage(LoGTpl, 'LoG', show=True)
   # if plot: plotLineHisto(LoGTpl[gsize])

    for ri in range(-rad, rad+1):
        for ci in range(-rad, rad + 1):
            r2 =  math.sqrt(ri*ri + ci*ci)
            if r2 > radedge:
                circularEdge[ri+rad, ci+rad] = 0

    template = cv2.filter2D(circularEdge, -1, LoGTpl)
   # if plot: showImage(template, 'DoG', show=True)
   # if plot: plotLineHisto(template[rad])
    return(template)
    #denoising of image through gausian filter

def readImage(file):
    if file[-4:] == '.dcm':
        dimg = pydicom.dcmread(file)   # read the dicom image like ct mri
        imgf = dimg.pixel_array     # extract the pixel data from the dicom image file
        img = np.uint8(imgf * (255 / np.max(imgf)))  # to create ndarray of bytes needed for displaying image
    else:
        img = cv2.imread(file, 0)
        img = cv2.resize(img, (256, 256))
    return (img)

def findMaxCorrelation(img, rho, sigma):
    cuRMAX, maxloc = 0, (0,0)
    for s in range (0, 1):
        LoGTpl = LoGDisc(rho+s, sigma)
        CorImg = templateMatching(img, LoGTpl)
        loc, max = findMaxRegion(CorImg)
        #showImage(CorImg, output, show=True)
        if max > cuRMAX:
            cuRMAX = max
            maxloc = loc
            maxs = s
            cimg = CorImg
          #  print('current max and location is for s ', max, loc, maxs)

    return(cimg, maxloc, maxs)
#to find the region of max corelation for an image
#region whhere pixels are correlating most acc to the templete

def getStrip(img, xc, yc):

    strip = np.zeros((360, RMAX - RMIN), np.uint8)

    for theta in range(360):
        th = theta * 2 * np.pi / 360
        for r in range(RMIN, RMAX):
            x = min(255, int(xc + r * np.cos(th) + 0.5))
            y = min(255, int(yc + r * np.sin(th) + 0.5))
            strip[theta, r - RMIN] = img[y, x]

    #showImage(strip,show=True)
    return (strip)

def verifyLoc(img, loc):
    diff = lambda v1, v2: abs(v1-v2)+1 if v1+v2 != 0 else 10

    strip = getStrip(img, loc[0], loc[1])
    #hist = cv2.calcHist([strip], [0], None, [256], [0,256])
    #plt.plot(hist), plt.show()
    thresh = 20
    strip[strip < thresh] = 0

    stripMax = np.zeros(360)
    for th in range(360):
        stripMax[th] = np.argmax(strip[th, :])+1

    score = 0
    for th in range(359):
        score += 1 / diff(stripMax[th], stripMax[th+1])

    return (score)

THRESHOLD = 7
inRange = lambda pi, ci, edges: True if abs(edges[pi] - edges[ci]) < THRESHOLD and edges[ci] != 0 else False

def longestRun(maxEdge):
    h, i = maxEdge.shape[0], 1
    best, st, len = 0, 0, 1
     #i=0
    while i < h:
        while i < h and inRange(st, i, maxEdge): i += 1 # find the first run without a discontinuity
        if i-st > len:
            best, len = st, i-st
        else: st = i
    avg = maxEdge[best:best+len].sum() / len
    return avg

def removeOutliers(maxEdge):
    # replace edge points that are missing by interpolating with next valid edge point and previous point

    h, i = maxEdge.shape[0], 1
    #print(f"maxedge shape:{maxEdge.shape, 1}")
    avg = longestRun(maxEdge)
    maxEdge[0], maxEdge[h-1] = avg, avg # the first and last edge indexes are set to average of longest run
    # so that discontinuity is checked with respect to that
    #i=0
    while i < h - 1:
        while i < h and inRange(i-1, i, maxEdge): i += 1 # find the first row where there is a discontinuity

        j = i + 1
        while j < h and inRange(i-1,j,maxEdge) == False: j += 1
        # find the next edge pixel that will be used for interpolation (pixel i to j-1)
        # rows in the range i to j have no edges (maxEdge = 0) so they should be interpolated
        for k in range(i, j-1):
          #try:
            maxEdge[k] = maxEdge[i - 1] + (maxEdge[j] - maxEdge[i - 1]) * (k - i + 1) // (j - i + 1)
          #except Exception as e:
          #  print(f"Exception: {e} for value of k:{k} i: {i} j: {j}")
        i = j + 1  # Edge pixel upto j checked and interpolated. The net edge pixel to be checked for interpolation
    return

def adjustBoundary(strip, maxIDs):
    #Finds edges where there is a discontinuity wrt previous edge and replaces with best edge in the neighbourhood
    h, w = strip.shape[:2]
    for j in range(1, h):
        pidx, nidx = maxIDs[j-1], maxIDs[j] # index of current and previous edge
        if abs(nidx-pidx) > 3:  # There is a gap that needs to be filled with best edge nearest to it
            max, idx = 0, nidx
            for i in range(pidx-2, pidx+3):
                if i >= w-MASK_SIZE or i < MASK_SIZE: continue
                corr = np.sum(strip[j,i-MASK_SIZE:i+MASK_SIZE] * mask)
                if corr-(nidx-i)**2 > max: max, idx = corr, i
            maxIDs[j] = idx
    return

OVERLAP = 10

def smoothBoundary(pts):
    h = pts.shape[0]
    extEdges = np.zeros((h+2*OVERLAP), int)
    extEdges[OVERLAP:h+OVERLAP] = pts
    extEdges[0:OVERLAP] = pts[h-OVERLAP:]    # reversing the last OVERLAP items
    extEdges[h+OVERLAP:] = pts[0:OVERLAP]

    smooth_intpts = np.array(savgol_filter(extEdges,101,3), int)
    return(smooth_intpts[OVERLAP:h+OVERLAP])

def progress(value, max=300):
    return HTML("""
        <progress
            value='{value}'
            max='{max}',
            style='width: 100%'
        >
            {value}
        </progress>
    """.format(value=value, max=max))

def show3dImage():
  
  global DISPLAY

  rho, sigma = RADIUS, SPREAD
  
  #fig = plt.figure()
  #ax = plt.axes(projection="3d")
  #ax= Axes3D(fig)
  xl=[]
  yl=[]
  zl=[]
  xs=[]
  ys=[]
  zs=[]
  count= 0
  carotid_pts=[]
  print("Generating 3D model of Artery...")
  out = display(progress(0, 300), display_id=True)
  for i in range(0,300):
    out.update(progress(i, 300))
    #nm=str(i)
    #name=path+'US000'+nm+'.png'
    #print(name)
    #img = readImage(path+'US000'+nm+'.png')
    name = path+"US0003_{:04d}.png".format(i)  
    
    if os.path.exists(name):
      try:
        
        img = readImage(name)
        #print(i)
        cimg, loc, maxs = findMaxCorrelation(img, rho, sigma)
        #print ('max location is: ', maxloc)
  
        BPts= getBoundary(img,loc)
        carotid_pts = np.array(getCarotidPts(img))
        x_mean = np.mean(carotid_pts[:,0])
        x_std = np.std(carotid_pts[:,0])
        #print(carotid_pts)
        #print(carotid_pts[:,0])
        #print(f"x mean : {x_mean}  x std : {x_std}")
        y_mean = np.mean(carotid_pts[:,1])
        y_std = np.std(carotid_pts[:,1])
        #print(carotid_pts[:,1])
        #print(f"x mean : {y_mean}  x std : {y_std}")
        threshold = 0.1
        for i in carotid_pts:
          zx =(i[0]-x_mean)/x_std
          zy =(i[1]-y_mean)/y_std
          
          #print(f"zx : {zx}  zy:{zy}")
          if zx < threshold and zy < threshold:
            xs.append(i[0])
            ys.append(i[1])
            zs.append(count)
          #else:
            #print(f" outlier ({i[0]},{i[1]}) removed ")
        #print(carotid_pts)
        x=[]
        y=[]
        z=[]
        for t in range(360):
            th = t * 2 * np.pi / 360
            xp = int(loc[0] + (BPts[t] + RMIN) * np.cos(th) + 0.5)
            yp = int(loc[1] + (BPts[t] + RMIN) * np.sin(th) + 0.5)
            x.append(xp)
            y.append(yp)
            z.append(count)

        #xl.extend(x)
        #yl.extend(y)
        #zl.extend(z)
        xl.append(x)
        yl.append(y)
        zl.append(z)
        #colours.append("#FF0000")
        #colours.append([count,"#FF0000"])
        count+=5

      except Exception as e:
        pass
        #print(f"error for file: {name}: {e}")



  fig = go.Figure(data=[go.Surface(z=zl, x=xl, y=yl,colorscale="Reds_r"),go.Scatter3d(x=xs,y=ys,z=zs,mode='markers',marker=dict(size=7,color=zs,colorscale='reds',opacity=0.8))])#,surfacecolor=colours)#,layout={'colorscale':{'sequential':colours}})
  
  fig.update_layout(title='Artries visualization', autosize=True,)
  
  #fig.update_traces(autocolorscale=False, selector=dict(type='surface'))
  #fig.update_layout(colorscale={'sequential':colours})
  #fig.update_traces(surfacecolor=colours, selector=dict(type='surface'))
  #fig.show()
  now = datetime.now()
  dt_string = now.strftime("%d_%m_%Y_%H_%M")
  fig.write_html(f"/content/sample_data/Ultrasound_{dt_string}.html")
  files.download(f"/content/sample_data/Ultrasound_{dt_string}.html")
  print("Model generated and downloaded successfully !!")

def getEdgeMap(strip):
    levels, nodes = strip.shape[:2]
    corim = np.zeros((levels, nodes), int)
    corim[:,0] = 1  # The first col on each row is set to 1 so that if there are no edges on a row then also there
    # will be one non-zero pixel

    for lvl in range(levels):
        for nd in range(MASK_SIZE, nodes-MASK_SIZE):
            corim[lvl, nd] = int(np.sum(strip[lvl, nd-MASK_SIZE:nd+MASK_SIZE] * mask))
    return (corim)
 # applying edge detector

def getBoundary(im, loc):
    strip = getStrip(im, loc[0], loc[1])
    edgeIm = getEdgeMap(strip)
    h, w = edgeIm.shape
    maxEdge = np.argmax(edgeIm, axis=1)
    i = 1  # The first edge (i = 0) is considered to be a valid one (as it is set to average value)

    
    #plt.subplot(311), plt.imshow(np.transpose(edgeIm)), plt.plot(maxEdge)
    removeOutliers(maxEdge)
    #plt.subplot(312), plt.imshow(np.transpose(edgeIm)), plt.plot(maxEdge)
    adjustBoundary(strip, maxEdge)
    #plt.subplot(313), plt.imshow(np.transpose(edgeIm)), plt.plot(maxEdge), plt.show()
    smoothBPts = smoothBoundary(maxEdge)
    #plt.figure(1)
    #plt.imshow(np.transpose(edgeIm))
    #plt.plot(smoothBPts), plt.show(block=True)

    return(smoothBPts)

def getCarotidPts(img):
    import matplotlib.pyplot as plt
    import statistics
    from scipy import stats as st
    import math

    global DISPLAY
    plt.clf()
    rho, sigma = RADIUS, SPREAD
    #img = readImage(img)
    #img_arr = np.asarray(img)
    cimg, loc, maxs = findMaxCorrelation(img, rho, sigma)
    BPts= getBoundary(img,loc)
    carotidPts = []
    carotidPts2 = []
    carotidPts3 = []
    carotidPts4 = []
    positions = []
    pixel_intensity=[]
    for t in range(360):
        th = t * 2 * np.pi / 360
        x = int(loc[0] + (BPts[t] + RMIN) * np.cos(th) + 0.5)
        y = int(loc[1] + (BPts[t] + RMIN) * np.sin(th) + 0.5)
        carotidPts.append((x, y))
        
    carotidPts = np.array(carotidPts)
    
    x_points = [i[0] for i in carotidPts]
    y_points = [i[1] for i in carotidPts]
    
    x_mid= (min(x_points)+max(x_points))/2
    y_mid= (min(y_points)+max(y_points))/2
    #print(f"for x mid points :{x_mid}")
    #print(f"for y mid point :{y_mid}")
    stepSize = 0.1
    r = 15
    t = 0
    while t < 2 * math.pi:
      positions.append((r * math.cos(t) + x_mid, r * math.sin(t) + y_mid))
      t += stepSize
    
    #print(positions)
    #print(type(positions))
    
    positions = np.array(positions)
    x_points2 = [int(i[0]) for i in positions]
    y_points2 = [int(i[1]) for i in positions]
    for yp in range(min(y_points2),max(y_points2)):
      if yp in y_points2:
        xe=[]
        for i, elem in enumerate(y_points2):
          if elem == yp:
            xe.append(x_points2[i])
        for xp in range(min(xe),max(xe)):
          #if xp in x_points2:
            carotidPts3.append((xp,yp))
            pixel_intensity.append(img[xp][yp])

    carotidPts3 = np.array(carotidPts3)
    
    #print(pixel_intensity.count(90))
    #print(statistics.mean(pixel_intensity))
    pixel_intensity2 = list(set(pixel_intensity))
    pixel_intensity2.sort(reverse=False)
    pixel_intensity2 =  pixel_intensity2[0:10]
    #print(pixel_intensity2)

    for point in carotidPts3:
      if img[point[0]][point[1]] not in range(24,26):
        pass
      else:
        carotidPts4.append((point[0],point[1]))
        
    #print(len(carotidPts4))
    
      
    #carotidPts4 = np.array(carotidPts4)
    #positions = np.array(positions)
    #print(img[132][68])
    #plt.figure(1)
    #plt.imshow(img, cmap='gray'), plt.title('Image with boundary detected')
    #plt.plot(carotidPts[:, 0], carotidPts[:, 1], 'r-', linewidth=2)
    #plt.plot(positions[:, 0], positions[:, 1], 'y-', linewidth=2)
    #plt.plot(carotidPts4[:, 0], carotidPts4[:, 1], 'y+', linewidth=2)
    #plt.plot([132],[68],'r+',linewidth=2)
    #plt.show(block=True)
    return carotidPts4
#for ploting boundary of artery over an image

def main():
  
  show3dImage()

main()

"""# End of code"""


